import { paths } from "./paths.js";
import { writeTextAtomic } from "./fsutil.js";

const PLUGIN_NAME = "@dsh-boot/restart-plugin";
const ROW_ID = "dsh-boot-restart";

export { PLUGIN_NAME, ROW_ID };

/**
 * Write the one-shot `--patch` overlay used by every dsh-boot launch.
 *
 * The overlay only adds the restart plugin row to the composed profile. It
 * never edits `$DSH_HOME/cordis.patch.yml` or
 * `$DSH_HOME/profiles/web/cordis.patch.yml`, so the user's own dsh
 * configuration stays untouched.
 */
export function writeInjectedPatch() {
  const yaml = `# Generated by dsh-boot. Do not edit: this file is rewritten on every start.
# Injects the bundled restart plugin as a --patch overlay. The user's
# cordis.patch.yml and profile manifest are never modified.
- insert:
    - id: ${ROW_ID}
      name: '${yamlQuote(PLUGIN_NAME)}'
`;
  writeTextAtomic(paths.patchFile, yaml);
  return paths.patchFile;
}

function yamlQuote(value) {
  return value.replaceAll("'", "''");
}
